In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_frame = pd.read_csv('final_dataset.csv')
data_frame.head(10)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2494,2495,2496,2497,2498,2499,Emotion,Age,Color,Gender
0,0,45,52,69,127,148,111,99,106,106,...,15,13,13,10,10,12,Emotion_Happy,Age_below20,E_White,G_Male
1,1,107,109,107,107,107,111,122,119,124,...,72,66,62,63,64,66,Emotion_Happy,Age_20_30,E_White,G_ Female
2,2,159,163,166,171,149,90,65,64,73,...,215,222,224,224,225,227,Emotion_Happy,Age_20_30,E_Hispanic,G_ Female
3,3,178,161,69,32,49,50,40,40,52,...,252,252,253,252,251,249,Emotion_Happy,Age_20_30,E_White,G_ Female
4,4,117,104,100,119,136,160,169,168,159,...,180,177,153,133,153,149,Emotion_Happy,Age_20_30,E_White,G_ Female
5,5,235,236,235,229,217,195,168,139,109,...,56,61,72,82,89,94,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
6,6,119,117,115,113,108,102,97,91,86,...,47,53,55,56,57,58,Emotion_Neutral,Age_below20,E_White,G_ Female
7,7,80,81,81,81,82,82,83,83,84,...,86,86,85,85,85,85,Emotion_Neutral,Age_20_30,E_White,G_ Female
8,8,163,166,167,170,176,183,191,201,208,...,228,229,229,229,229,229,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
9,9,174,174,175,177,177,176,176,175,175,...,150,138,138,148,159,167,Not_Face,0,0,0

In [3]:
data_frame['Emotion'].value_counts()

Not_Face           138
Emotion_Neutral    127
Emotion_Happy       66
Emotion_Sad         10
Emotion_Angry        7
Age_30_40            1
Age_above_50         1
0                    1
Name: Emotion, dtype: int64

In [4]:
def isFace(x):
    
    if x == 'Not_Face':
        return 0
    else:
        return 1

In [19]:
X = data_frame.iloc[:,1:2501]
y = data_frame['Emotion'].apply(isFace)

In [20]:
y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      0
10     0
11     0
12     0
13     0
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     0
24     0
25     1
26     1
27     1
28     0
29     1
      ..
321    1
322    1
323    1
324    1
325    1
326    1
327    1
328    1
329    1
330    1
331    1
332    1
333    1
334    1
335    1
336    1
337    1
338    0
339    0
340    0
341    1
342    0
343    0
344    0
345    1
346    1
347    1
348    1
349    0
350    1
Name: Emotion, Length: 351, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [23]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [24]:
y_train

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
from keras.layers import Dense
from keras.layers import MaxPooling2D
from keras.layers import Convolution2D
from keras.layers import Flatten
from keras.models import Sequential

Using TensorFlow backend.

In [27]:
model = Sequential()
model.add(Convolution2D(30,3, input_shape = (50,50,1), activation = 'relu', padding = 'same'))
model.add(MaxPooling2D(pool_size= (2,2)))
model.add(Convolution2D(40,3, activation = 'relu', padding = 'same'))
model.add(Convolution2D(45,3, activation = 'relu', padding = 'same'))
model.add(MaxPooling2D(pool_size= (2,2))) 
model.add(Convolution2D(50,3, activation = 'relu', padding = 'same'))
model.add(Flatten())
model.add(Dense(output_dim = 128, activation = 'relu'))
model.add(Dense(output_dim = 1, activation = 'sigmoid'))

WARNING:tensorflow:From C:\Users\Dell\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

C:\Users\Dell\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`
  if __name__ == '__main__':
C:\Users\Dell\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  # Remove the CWD from sys.path while we load stuff.

In [28]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics  = ['accuracy'])

In [29]:
trainX = X_train.reshape(X_train.shape[0],50, 50, 1).astype( 'float32' )
testX = X_test.reshape(X_test.shape[0],50, 50, 1).astype( 'float32' )

In [30]:
model.fit(trainX, y_train, batch_size=50, epochs = 10)

WARNING:tensorflow:From C:\Users\Dell\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
235/235 [==============================] - 5s 22ms/step - loss: 0.6738 - acc: 0.5915
Epoch 2/10
235/235 [==============================] - 3s 11ms/step - loss: 0.5314 - acc: 0.7404
Epoch 3/10
235/235 [==============================] - 3s 11ms/step - loss: 0.5177 - acc: 0.7830
Epoch 4/10
235/235 [==============================] - 3s 11ms/step - loss: 0.4435 - acc: 0.7957
Epoch 5/10
235/235 [==============================] - 3s 11ms/step - loss: 0.4033 - acc: 0.8340
Epoch 6/10
235/235 [==============================] - 3s 11ms/step - loss: 0.3308 - acc: 0.8681
Epoch 7/10
235/235 [==============================] - 3s 11ms/step - loss: 0.2862 - acc: 0.8894
Epoch 8/10
235/235 [==============================] - 3s 11ms/step - loss: 0.2182 - acc: 0.9277
Epoch 9/10
235/235 [==============================] - 3s 12ms/step - loss: 0.1921 - acc: 0.9234
Epoch 10/10
235/235 [==============================] - 3s 11ms/step - loss: 0.1470 - acc: 0.9489

In [31]:
score = model.evaluate(testX, y_test, batch_size=10)

116/116 [==============================] - 1s 9ms/step

In [32]:
score

[0.6692574959376763, 0.784482749371693]

In [33]:
model_json = model.to_json()
with open("face.json", "w") as json_file:
    json_file.write(model_json)
    
#serialise weights as HDF5

model.save_weights("face.h5")
print("Saved")

Saved